---
title: "sata_sort_Jon1"
author: "Jonathan Fielder"
date: '2022-11-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}
library(tidyverse)
library(dplyr)
library(readxl)
Juris15 <- read_excel("Juris15.xlsx")
Juris16 <- read_excel("Juris16.xlsx")
Juris17 <- read_excel("Juris17.xlsx")
Juris18 <- read_excel("Juris18.xlsx")
Juris19 <- read_excel("Juris19.xlsx")
SchoolGrades15 <- read_excel("SchoolGrades15.xls")
SchoolGrades16 <- read_excel("SchoolGrades16.xls")
SchoolGrades17 <- read_excel("SchoolGrades17.xls")
SchoolGrades18 <- read_excel("SchoolGrades18.xls")
SchoolGrades19 <- read_excel("SchoolGrades19.xls")
```



```{r crime short}
crime15 <- Juris15
crime16 <- Juris16
crime17 <- Juris17
crime18 <- Juris18
crime19 <- Juris19

colnames(crime16) <- colnames(crime15)
colnames(crime17) <- colnames(crime15)
colnames(crime18) <- colnames(crime15)
colnames(crime19) <- colnames(crime15)


crime_15_19 <- rbind.data.frame(crime15, crime16, crime17, crime18, crime19)
```



```{r school sort}
grades15 <- SchoolGrades15[ -c(5:15,17,24)]
grades16 <- SchoolGrades16[ -c(5:19,21:23,30)]
grades17 <- SchoolGrades17[ -c(5:19,21:40,47)]
grades18 <- SchoolGrades18[ -c(5:19,21:41,48)]
grades19 <- SchoolGrades19[ -c(5:19,21:42)]


## oops more to get rid of
grades15 <- grades15[ -c(1,3,8,9)]
grades16 <- grades16[ -c(1,3,8,9)]
grades17 <- grades17[ -c(1,3,8,9)]
grades18 <- grades18[ -c(1,3,8,9)]
grades19 <- grades19[ -c(1,3,8,9)]



grades15 <- grades15 %>%
  mutate(Year = (2015))
grades16 <- grades16 %>%
  mutate(Year = (2016))
grades17 <- grades17 %>%
  mutate(Year = (2017))
grades18 <- grades18 %>%
  mutate(Year = (2018))
grades19 <- grades19 %>%
  mutate(Year = (2019))
  

colnames(grades16) <- colnames(grades15)
colnames(grades17) <- colnames(grades15)
colnames(grades18) <- colnames(grades15)
colnames(grades19) <- colnames(grades15)









## combine all years
grades15_19 <- rbind(grades15, grades16, grades17, grades18, grades19)

## rename to grade
colnames(grades15_19)[3] ="Grade"

## rename to county
colnames(grades15_19)[1] ="County"


## logic to numbers (100 yes 2 no) easier to switch to percent

grades15_19$`Charter School` <-ifelse(grades15_19$`Charter School` == "YES",100,0)
grades15_19$`Title 1` <-ifelse(grades15_19$`Title 1` == "YES",100,0)




## grades letters to numbers i.e. A=4 B=3 C=2 D=1 F=0
grades15_19 <- grades15_19 %>%
  mutate(Grade=ifelse(Grade == "A",4,Grade),
         Grade=ifelse(Grade == "B",3,Grade),
         Grade=ifelse(Grade == "C",2,Grade),
         Grade=ifelse(Grade == "D",1,Grade),
         Grade=ifelse(Grade == "F",0,Grade),
         Grade=ifelse(Grade == "I",5,Grade))


## removes incomplete grade schools for each year the data was not good for the school grade
grades15_19 <- subset(grades15_19, Grade != 5)

## remove incomplete minority percentages
colnames(grades15_19)[6] = "Minority"
grades15_19 <- grades15_19 %>%
mutate(Minority=ifelse(Minority == ".",200,Minority))
grades15_19 <- subset(grades15_19, Minority != 200)

## remove NA disadvantage
colnames(grades15_19)[7] = "Dis"
grades15_19 <- grades15_19 %>%
mutate(Dis=ifelse(Dis == ".",200,Dis))
grades15_19 <- subset(grades15_19, Dis != 200)


## summarize by county
countyGrades15_19 <- grades15_19 %>%
  group_by(County, Year) %>%
  summarize(`Title 1` = mean(as.numeric(`Title 1`)), 
            Grade = mean(as.numeric(Grade)),
            `Charter School` = mean(as.numeric(`Charter School`)),
            Minority = mean(as.numeric(Minority)),
            Disadvantaged = mean(as.numeric(Dis)))


## rename columns to reflect data
colnames(countyGrades15_19)[3] = "Percentage of Title 1 Schools"
colnames(countyGrades15_19)[4] = "Grade (0 = F, 4 = A)"
colnames(countyGrades15_19)[5] = "Percentage of Charter Schools"
colnames(countyGrades15_19)[6] = "Percentage of Minority Students"
colnames(countyGrades15_19)[7] = "Percentage of Economically Disadvantaged Students"
  
```


countyGrades15_19 is the Melange